#!/bin/bash
#
# low battery warning
#

systemctl --user import-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS

battery_level=$(acpi -b | cut -d ' ' -f 4 | grep -o '[0-9]*')
ac_power=$(acpi -b | grep -c "Charging")

if [[ $ac_power -eq 0 && $battery_level -le 15 ]]; then
	notify-send "Critical battery" "Battery level is ${battery_level}" -u critical
fi
