#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Neovim
rg --color=always --line-number --no-heading --smart-case "${*:-}" |
	fzf --ansi \
		--multi \
		--select-1 --exit-0 \
		--color "hl:-1:underline,hl+:-1:underline:reverse" \
		--delimiter : \
		--preview 'bat --color=always {1} --highlight-line {2}' \
		--preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
		--bind 'enter:become(nvim --server ~/.cache/nvim/server.pipe --remote {1} +{2})'
