#!/usr/bin/zsh

# -------------------------------------------------------------------
# General
# -------------------------------------------------------------------

alias history='fc -fl 1'

# Helpers
alias fa="alias | $FZF_COMMAND"
alias trash='trash-put'
alias sz="source $ZSHRC"
alias cat="bat"
alias sys='systemctl'
alias o='mimeopen'
alias lazygit='TERM=xterm-256color lazygit'
alias c='clear'

# Scripts
alias work="source $HOME/.screenlayout/work.sh"
alias home="source $HOME/.screenlayout/home.sh"

# Tools
alias weather='curl wttr.in/campos_dos_goitacazes'
alias ngrok="$HOME/Projects/tools/ngrok"
alias zlt="time zsh -i -c exit"
alias sha='shasum -a 256 '

if [ -z "$MACOS" ]; then
	# Xclip
	alias pbcopy='xclip -selection clipboard'
	alias pbpaste='xclip -selection clipboard -o'
fi

# Compress and Extract
alias zip='zip -r'
alias tarc='tar -czpvf'
alias untar='tar -xzpvf'

# Shortcuts
alias todo="$EDITOR ~/Projects/personal/files/todo"
alias zshrc="$EDITOR $ZSHRC"
alias tmuxconf="$EDITOR $TMUXCONF"
alias nvimrc="$EDITOR $VIMRC"

# -------------------------------------------------------------------
# Network
# -------------------------------------------------------------------

alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ping='ping -c 5'
alias ipe='curl ipinfo.io/ip'

# Manager
alias nds='nmcli device status'
alias ncs='nmcli connection show'
alias ncsa='nmcli connection show --active'
alias ndw='nmcli dev wifi'

# -------------------------------------------------------------------
# GNU Tools
# -------------------------------------------------------------------

# Sudo
alias sudo="nocorrect sudo"
alias _="sudo"
alias please='sudo'

# Process
alias psa='ps awux | less'
alias ka='killall'
alias k='kill -9'
alias j='jobs -l'

function kp() {
	k $(pgrep "$1")
}

# Type
alias tp='type -a'

# Space
alias df="df -H"
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"

# Storages
alias lsblk='lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL,UUID'

# Directories
alias md='mkdir -p'

# Copy
alias cpr='cp -R'

# Remove
alias rm='rm -i'
alias rf='rm -rend'
alias rfa='rm -rend *'

# Move
alias mv='mv -i'

# Lists
alias l='ls -lah --group-directories-first'
alias ll='ls -lh'
alias lsd='ls --group-directories-first'
alias lld='ll --group-directories-first'
alias lh='ls -a | egrep "^\."'
alias l.='ls -d .* --color=auto'

# -------------------------------------------------------------------
# Package manager
# -------------------------------------------------------------------
if [ -z "$MACOS" ]; then
	alias mpsi='makepkg -si'

	# Package manager
	alias y='paru'
	alias update='y -Syu'
	alias install='y -S'
	alias search='y -Ss'
	alias purge='y -Rns'
	alias clean='purge $(y -Qtdq)'

	# Mirrors
	alias mirrors="_ reflector --verbose --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
else
	alias b='brew'
	alias update='b upgrade'
	alias install='b install'
	alias search='b search'
	alias purge='b remove'
	alias clean='b cleanup'
fi

# -------------------------------------------------------------------
# Plugins and apps
# -------------------------------------------------------------------

# Nvim
alias nv='nvim'

# NNN
alias nn='nnn -l'

# Eza
alias ls=eza
(($ + commands[eza])) && tree='eza --color=always -T' || tree='tree -Ctr'

alias au='zinit update --parallel'
alias irssi='commnad irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi'

# -------------------------------------------------------------------
# Languages
# -------------------------------------------------------------------

# Rails
alias s='spring'
alias srs='s rails s'
alias src='s rails c'
alias rddl='rake db:drop:all'
alias rre='rddl && rdc && rdm && rds'
alias rrf="rake routes | $FZF_COMMAND"

# Bundle
alias be="bundle exec"
alias ber="be rake"

# Rbenv
alias rb='rbenv'
alias rbg='rb gemset'
alias rbr='rb rehash'

# Npm
alias ns='npm start'
alias ys='yarn start'
alias yb='yarn build'
alias yw='yarn watch'
alias yt='yarn test'

# -------------------------------------------------------------------
# Tools
# -------------------------------------------------------------------

# Git
alias glog="git log --graph --oneline --decorate --date-order --color --boundary"
alias git-branch="git symbolic-ref --short HEAD"
eval "$(hub alias -s)"

# Heroku
alias he="heroku"
alias heb="he run bundle exec"
alias hrc="heb rails c"
alias hrdm="heb rake db:migrate"
alias hrds="heb rake db:seed"
alias hrdsl="heb rake db:schema:load"
alias hl="he logs -t"

# Docker
alias dc="docker compose"
alias dcu="dc up"
alias dcd="dc down"

# Vim-plug
alias pi="$EDITOR +PackerInstall"
alias pc="$EDITOR +PackerClean"
alias pu="$EDITOR +PackerSync"

# Tmux
alias tm="tmux -2 -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias tmka="tm ls | grep : | cut -d. -f1 | awk '{print substr($1, 0, length($1)-1)}' | xargs kill"
alias tks='tmux kill-server'
alias tkst='tmux kill-session -t'
alias ta='tmux at'

# Foreman with Procfiles
alias fs='be foreman start -f Procfile.development'
alias fsdocker='be foreman start -f Procfile.docker'
