#!/usr/bin/zsh

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ":completion:*" show-ambiguity "$color[fg-red]"
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' menu no

zstyle ':fzf-tab:complete:cd:*' fzf-preview 'command ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'command ls --color $realpath'
