#!/usr/bin/zsh

# -------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------

function gphm {
  git push heroku ${1:-master}:master
}

function vmi {
  $EDITOR $(ls -td db/migrate/* | head -1)
}

function gcof {
  git checkout $(git branch | fzf)
}

function lipsum {
  curl -s -H 'Content-Type: application/json' -X POST https://lipsum.com/feed/json | jq -r '.feed.lipsum' | xclip -selection c
}

function nvre {
  arr=($(nvr --serverlist))
  nvr --servername=${arr[1]} --remote "$1"
}

function source_file_if_exists {
  [[ -f "$1" ]] && source "$1"
}

# Install (one or multiple) selected application(s)
# using "brew search" as source input
# mnemonic [B]rew [I]nstall [P]ackage
bip() {
  local inst=$(brew search "$@" | fzf -m)

  if [[ $inst ]]; then
    for prog in $(echo $inst);
    do; brew install $prog; done;
  fi
}

# Update (one or multiple) selected application(s)
# mnemonic [B]rew [U]pdate [P]ackage
bup() {
  local upd=$(brew leaves | fzf -m)

  if [[ $upd ]]; then
    for prog in $(echo $upd);
    do; brew upgrade $prog; done;
  fi
}

# Delete (one or multiple) selected application(s)
# mnemonic [B]rew [C]lean [P]ackage (e.g. uninstall)
bcp() {
  local uninst=$(brew leaves | fzf -m)

  if [[ $uninst ]]; then
    for prog in $(echo $uninst);
    do; brew uninstall $prog; done;
  fi
}
