#!/usr/bin/zsh

# Load library
[ -f $XDG_CONFIG_HOME/fzf/fzf.zsh ] && source $XDG_CONFIG_HOME/fzf/fzf.zsh 2>/dev/null

export FZF_DEFAULT_OPTS="
  --cycle
  --bind=ctrl-b:preview-up
  --bind=ctrl-f:preview-down
  --bind=ctrl-d:half-page-down
  --bind=ctrl-u:half-page-up
  --bind=alt-a:select-all
  --bind=ctrl-r:toggle-all
  --bind=ctrl-s:toggle-sort
  --bind=\):toggle-preview
  --bind=alt-w:toggle-preview-wrap
  --bind='alt-e:execute($EDITOR {})+abort'"
