#!/usr/bin/sh

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
	mkdir -p "$(dirname $ZINIT_HOME)"
	git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source zinit
source "${ZINIT_HOME}/zinit.zsh"

# Load a few important annexes, without Turbo (this is currently required for annexes)
zinit light-mode for \
	zdharma-continuum/zinit-annex-as-monitor \
	zdharma-continuum/zinit-annex-bin-gem-node \
	zdharma-continuum/zinit-annex-patch-dl \
	zdharma-continuum/zinit-annex-rust

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

zinit wait lucid light-mode for \
	Aloxaf/fzf-tab \
	lukechilds/zsh-nvm \
	unixorn/git-extra-commands \
	MichaelAquilina/zsh-you-should-use \
	zsh-users/zsh-history-substring-search \
	hlissner/zsh-autopair \
	wfxr/forgit \
	wfxr/formarks \
	atuinsh/atuin

zinit wait lucid for \
	atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
		zdharma-continuum/fast-syntax-highlighting \
	blockf \
		zsh-users/zsh-completions \
	atload"!_zsh_autosuggest_start; \
		bindkey -M viins '^@' autosuggest-accept" \
		zsh-users/zsh-autosuggestions

zinit snippet OMZP::git
zinit snippet OMZP::git-extras
zinit snippet OMZP::rails
zinit snippet OMZP::heroku
zinit snippet OMZP::command-not-found
zinit snippet OMZP::vi-mode
zinit snippet OMZP::archlinux
zinit snippet OMZP::web-search
zinit snippet OMZP::colored-man-pages

# Load completions
if (( ${+commands[brew]} )); then
	FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
autoload -Uz compinit && compinit
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit cdreplay -q
