#!/usr/bin/sh

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
	print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
	command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
	command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" &&
		print -P "%F{33} %F{34}Installation successful.%f%b" ||
		print -P "%F{160} The clone has failed.%f%b"
fi

# Source zinit
source "${ZINIT_HOME}/zinit.zsh"

# Load a few important annexes, without Turbo (this is currently required for annexes)
zinit light-mode for \
	zdharma-continuum/zinit-annex-as-monitor \
	zdharma-continuum/zinit-annex-bin-gem-node \
	zdharma-continuum/zinit-annex-patch-dl \
	zdharma-continuum/zinit-annex-rust

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

zinit wait lucid light-mode for \
	zsh-users/zsh-syntax-highlighting \
	zsh-users/zsh-completions \
	zsh-users/zsh-autosuggestions \
	Aloxaf/fzf-tab \
	lukechilds/zsh-nvm \
	unixorn/git-extra-commands \
	MichaelAquilina/zsh-you-should-use \
	zsh-users/zsh-history-substring-search \
	hlissner/zsh-autopair \
	wfxr/forgit \
	wfxr/formarks

zinit snippet OMZP::git
zinit snippet OMZP::git-extras
zinit snippet OMZP::rails
zinit snippet OMZP::heroku
zinit snippet OMZP::command-not-found
zinit snippet OMZP::vi-mode
zinit snippet OMZP::archlinux
zinit snippet OMZP::web-search
zinit snippet OMZP::colored-man-pages

# Load completions
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
autoload -Uz compinit && compinit
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit cdreplay -q
