#!/usr/bin/zsh

# Load library
source $ANTIGEN_HOME/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles
antigen bundles <<EOBUNDLES
  git
  git-extras
  rails
  heroku
  command-not-found
  vi-mode
  archlinux
  web-search
  colored-man-pages

  zdharma/fast-syntax-highlighting@main
  MichaelAquilina/zsh-you-should-use
  hlissner/zsh-autopair
  lukechilds/zsh-nvm
  unixorn/git-extra-commands@main

  wfxr/forgit
  wfxr/formarks

  zsh-users/zsh-autosuggestions
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-completions

  mafredri/zsh-async
  sindresorhus/pure@main
EOBUNDLES

# Tell Antigen that you're done.
antigen apply
