std = "std"

[lints]
  incorrect_standard_library_use = "allow" # Workaround for https://github.com/Kampfkarren/selene/issues/467
  mixed_table = "allow" # lazy.nvim uses that
  multiple_statements = "allow"
