windowrulev2 = float, title:^(1Password)$
windowrulev2 = float, class:^(1Password)$
windowrulev2 = size 800 500, title:^(1Password)$
windowrulev2 = center, title:^(1Password)$
windowrulev2 = stayfocused, class:^(1Password)$
windowrulev2 = noborder, class:^(1Password)$

windowrulev2 = float,class:^(floating-terminal)$
windowrulev2 = size 80% 80%,class:^(floating-terminal)$
windowrulev2 = center,class:^(floating-terminal)$
windowrulev2 = focusonactivate,class:^(floating-terminal)$
