format = """
$username\
$hostname\
$directory\
$git_commit\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " "
style = "blue"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[$untracked$modified](bold red)[($conflicted$staged$renamed$deleted)](bright-black) ($ahead_behind$stashed$diverged$typechanged$up_to_date)]($style) "
style = "cyan"
modified = "*"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
