#!/bin/bash

# scrot /tmp/screen.png
# convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png

# [[ -f $1 ]] && convert /tmp/screen.png $1 -gravity center -composite -matte /tmp/screen.png

# i3lock -u -i /tmp/screen.png
# rm /tmp/screen.png

icon="$HOME/.config/i3/lock.png"
img="$HOME/.cache/i3lock.png"

# Take a screenshot for our background
scrot $img

# Pixelate the background
convert $img -scale 10% -scale 1000% $img

# Add the lock-icon
convert $img $icon -gravity center -composite $img

# Pause notifications
notify-send "DUNST_COMMAND_PAUSE"

# Finally run i3lock itself
i3lock -n -u -i $img

# Resume notifications
notify-send "DUNST_COMMAND_RESUME"

# Remove image
rm $img
