#!/usr/bin/env ruby

Pry.config.editor = "nvim"

Pry.commands.alias_command 'c', 'continue'
Pry.commands.alias_command 's', 'step'
Pry.commands.alias_command 'n', 'next'
Pry.commands.alias_command 'l', 'whereami'
Pry.commands.alias_command 'rc', 'reload-code'
Pry.commands.alias_command 'b', 'break'
Pry.commands.alias_command 'bd', 'break --disable-all'
Pry.commands.alias_command 'dp', 'disable-pry'
Pry.commands.alias_command 'pl', 'play -l '
