#!/usr/bin/zsh

# Misc
alias fa="alias | $FZF_COMMAND"
alias history='fc -fl 1'

# Sudo
alias sudo="nocorrect sudo"
alias _="sudo"

# Space
alias df="df -H"
alias du="du -ch"
alias dus="du -sckx * | sort -nr"


# Directories
alias md='mkdir -p'
alias rd=rmdir

# Lists
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'
alias ls='ls --color=auto'
alias lh='ls -l .??*'
alias lhd='ls -ld .??*'
alias lh='ls -a | egrep "^\."'
alias ls=exa
(( $+commands[exa] )) && tree='exa --color=always -T' || tree='tree -Ctr'

# Package manager
alias t='aurman'
alias update='t -Syu'
alias install='t -S'
alias search='t -Ss'
alias purge='t -Rns'
alias clean='purge $(t -Qtdq)'

# Zsh
alias sz="source ~/.zshrc"
alias zlt="time zsh -i -c exit"

# Rails
alias s='spring'
alias srs='s rails s'
alias src='s rails c'
alias rddl='rake db:drop:all'
alias rre='rddl && rdc && rdm && rds'
alias rrf="rake routes | $FZF_COMMAND"

# Rbenv
alias rb='rbenv'
alias rbg='rb gemset'
alias rbr='rb rehash'

# Zplug
alias zu="zplug update"
alias zpc="zplug clean && zplug clear && sz"

# Git
alias glog="git log --graph --oneline --decorate --date-order --color --boundary"
eval "$(hub alias -s)"

# Nvim
alias nv='nvim'
alias pi="$EDITOR +PlugInstall"
alias pc="$EDITOR +PlugClean"
alias pu="$EDITOR +PlugUpdate"

# Tmux
alias tmux-kill-all="tmux ls | grep : | cut -d. -f1 | awk '{print substr($1, 0, length($1)-1)}' | xargs kill"

# Gem
gi() { gem install $@; rbenv rehash; rehash }

# Heroku
alias hrc="heroku run bundle exec rails c"
alias hrdm="heroku run bundle exec rake db:migrate"
alias hrds="heroku run bundle exec rake db:seed"
alias hrdsl="heroku run bundle exec rake db:schema:load"
alias hl="heroku logs -t"

# Config shortcuts
alias zshrc="$EDITOR $HOME/.zshrc"
alias tmuxconf="$EDITOR $HOME/.tmux.conf"
alias nvimrc="$EDITOR $HOME/.config/nvim/init.vim"

# Helper and apps
alias tog='toggl'
alias dot="cd $DOTFILES_PATH"
alias work="cd $PERSONAL_HOME"
alias strem="sh $HOME/.strem/Stremio.sh"
alias qute="$PERSONAL_HOME/installers/qutebrowser/.venv/bin/python3 -m qutebrowser \"$@\" --enable-webengine-inspector"
alias scon="$PERSONAL_HOME/installers/sconsify"
