#!/usr/bin/zsh

# -------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------

function gphm {
  git push heroku ${1:-master}:master
}

function vmi {
  $EDITOR $(ls -td db/migrate/* | head -1)
}

function gcof {
  git checkout $(git branch | fzf)
}

function lipsum {
  curl -s -H 'Content-Type: application/json' -X POST https://lipsum.com/feed/json | jq -r '.feed.lipsum' | xclip -selection c
}

function nvre {
  arr=($(nvr --serverlist))
  nvr --servername=${arr[1]} --remote "$1"
}
