require('settings')

require('maps')
require('commands')
require('plugins')
require('functions')

require('plugins.settings')
require('plugins.statusline')
require('plugins.bufferline')
require('plugins.lsp')
require('plugins.coc')
require('plugins.hop')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.cmp')
